#include <stdio.h>    
#include <stdlib.h>
#include <sys/utsname.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <dirent.h>
#include <sys/dir.h>
#include <sys/types.h>
#include <fcntl.h> 
#include <pwd.h>
#include <sys/stat.h>
#include <time.h>
#include <sys/wait.h>
#include <signal.h>
#include <time.h>